on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: build

jobs:
  render:
    name: build
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{secrets.GITHUB_TOKEN}}
      NOAA_KEY: ${{secrets.NOAA_KEY}}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install macOS dependencies for tbeptools
        run: |
          brew install cairo
          brew install gdal
          brew install udunits
          brew install xquartz
      - name: Install R packages
        run: |
          install.packages(c("remotes", "tidyverse", "extrafont", "reactable", "gridExtra", "english", "here", "rmarkdown", "bookdown", "ggfx", "ggmap", "ggsn", "ggrepel"))
          remotes::install_github("tbep-tech/tbeptools")
        shell: Rscript {0}
      - name: Render index
        run: Rscript -e 'rmarkdown::render("index.Rmd")'
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git commit -m 'Re-build Rmarkdown files' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
